#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// The official signature of the Trinary Star System Executable Environment
#define SEF_MAGIC 0x0043C0DE  /* SEF (3) + "3CODE" */

typedef struct {
    uint32_t magic;          // Must equal SEF_MAGIC (0x03C0DE03)
    uint32_t version;        // Format version (xxxx xxxx xxxx xxxx yyyy yyyy yyyy yyyy)
    uint64_t entry_point;    // Virtual address of the first instruction to execute
    uint64_t text_vaddr;     // Base virtual address where code expects to load
    uint64_t text_size;      // Total size of the executable code (.text) in bytes
    uint64_t data_size;      // Total size of initialized data (.data) in bytes
    uint64_t bss_size;       // Total size of uninitialized data (.bss) in bytes
} __attribute__((packed)) sef_header_t;

int main(int argc, char* argv[]) {
    if (argc < 3) {
        printf("Usage: %s <input.bin> <output.sef>\n", argv[0]);
        return 1;
    }

    // 1. Open the flat binary generated by GCC/LD
    FILE* infile = fopen(argv[1], "rb");
    if (!infile) {
        printf("Error: Could not open input file '%s'\n", argv[1]);
        return 1;
    }

    // Calculate file payload size
    fseek(infile, 0, SEEK_END);
    uint64_t bin_size = ftell(infile);
    fseek(infile, 0, SEEK_SET);

    // 2. Setup the official SEF header metadata
    sef_header_t header;
    memset(&header, 0, sizeof(sef_header_t));
    
    header.magic = SEF_MAGIC;
    header.version = (1 << 16) | 0; // OS Version 1.0 using your split-bit layout
    header.text_vaddr = 0x400000;    // Standard load point matching linker scripts
    header.entry_point = 0x400000;   // Execution entry line
    header.text_size = bin_size;     // Map flat payload bytes
    header.data_size = 0;            
    header.bss_size = 4096;          // Allocate 4KB page for uninitialized user space arrays

    // 3. Open the final output SEF file
    FILE* outfile = fopen(argv[2], "wb");
    if (!outfile) {
        printf("Error: Could not open destination file '%s'\n", argv[2]);
        fclose(infile);
        return 1;
    }

    // 4. Write the SEF header and append the payload
    fwrite(&header, sizeof(sef_header_t), 1, outfile);

    uint8_t* buffer = malloc(bin_size);
    if (!buffer) {
        printf("Error: Out of memory during conversion allocation.\n");
        fclose(infile);
        fclose(outfile);
        return 1;
    }

    fread(buffer, 1, bin_size, infile);
    fwrite(buffer, 1, bin_size, outfile);

    // Clean up
    free(buffer);
    fclose(infile);
    fclose(outfile);

    printf("Successfully baked SEF file: %s (Magic: 0x%08X)\n", argv[2], SEF_MAGIC);
    return 0;
}